---
# handlers for ansible-role-docker-nginx_exporter

- name: restart nginx_exporter
  service:
    name: nginx_exporter
    state: restarted
    enabled: true

- name: start nginx_exporter
  service:
    name: nginx_exporter
    state: started
    enabled: true

- name: reload nginx_exporter
  service:
    name: nginx_exporter
    state: reloaded
    enabled: true
